### ISSUE TITLE
Chore: Write integration tests

### ISSUE THREAD

**Issue by Shonyyyyy** [Shonyyyyy/do_it_again#13]

**Comment by TPei** [comment]
http://blog.thecodewhisperer.com/permalink/integrated-tests-are-a-scam/ ;)

**Comment by Shonyyyyy** [comment]
hater!

**Comment by TPei** [comment]
swag

**Comment by Shonyyyyy** [comment]
not necessary anymore, since controller tests are enough and basically are integration tests
